// Run with Node and Puppeteer installed; this starts its own local preview server.
const fs=require('node:fs/promises'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..');
const server=http.createServer(async(req,res)=>{try{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=path.resolve(root,'.'+(name==='/'?'/index.html':name));if(!file.startsWith(root+path.sep))throw Error();const bytes=await fs.readFile(file);res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css'})[path.extname(file)]||'application/octet-stream');res.end(bytes);}catch{res.statusCode=404;res.end();}});
const assert=require('node:assert/strict');const puppeteer=require('puppeteer');
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||undefined,headless:true,args:['--no-sandbox','--autoplay-policy=no-user-gesture-required']});try{
 const page=await browser.newPage();await page.setViewport({width:1280,height:950});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'networkidle0'});await page.$eval('details.help',el=>{el.open=true;});await page.click('#demo');await page.$eval('details.help',el=>{el.open=false;});await page.waitForFunction(()=>document.querySelector('#previewAudio').readyState>=1);
 await page.focus('#preview');await page.keyboard.press('Space');await page.waitForFunction(()=>document.querySelector('#play').textContent.includes('Pause'));assert.equal(await page.$eval('#previewAudio',e=>e.paused),false);
 await page.keyboard.press('Space');await page.waitForFunction(()=>document.querySelector('#play').textContent.includes('Play'));assert.equal(await page.$eval('#previewAudio',e=>e.paused),true);
 await page.click('#restart');await page.focus('#skipForward');await page.keyboard.press('Space');assert.equal(await page.$eval('#scrubber',e=>Number(e.value)),5);assert.equal(await page.$eval('#previewAudio',e=>e.paused),true);
 await page.click('#restart');let rect=await page.$eval('#preview',el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height};});await page.mouse.click(rect.x+rect.width*.8,rect.y+rect.height*.5);await page.mouse.click(rect.x+rect.width*.8,rect.y+rect.height*.5);assert.equal(await page.$eval('#scrubber',e=>Number(e.value)),5);assert.equal(await page.$eval('.jaw-skip-flash',e=>e.dataset.side),'right');
 await page.mouse.click(rect.x+rect.width*.2,rect.y+rect.height*.5);await page.mouse.click(rect.x+rect.width*.2,rect.y+rect.height*.5);assert.equal(await page.$eval('#scrubber',e=>Number(e.value)),0);
 await page.$eval('#editor',el=>el.scrollIntoView());await page.waitForSelector('.jaw-preview-shell.is-floating');await page.click('#floatingPlay');await page.waitForFunction(()=>!document.querySelector('#previewAudio').paused);await page.click('#floatingPlay');await page.waitForFunction(()=>document.querySelector('#previewAudio').paused);
 await page.focus('#floatingMove');await page.keyboard.press('ArrowLeft');await page.focus('#floatingResize');await page.keyboard.press('ArrowRight');
 await page.click('#floatingClose');assert.equal(await page.$('.jaw-preview-shell.is-floating'),null);await page.evaluate(()=>window.scrollTo(0,0));await new Promise(r=>setTimeout(r,100));await page.$eval('#editor',el=>el.scrollIntoView());await page.waitForSelector('.jaw-preview-shell.is-floating');
 await page.evaluate(()=>window.scrollTo(0,0));await page.waitForFunction(()=>!document.querySelector('.jaw-preview-shell').classList.contains('is-floating'));assert.equal(await page.$eval('#preview',e=>!!e.closest('.preview-stage')),true);
 await page.setViewport({width:390,height:844,isMobile:true,hasTouch:true});await page.$eval('details.help',el=>{el.open=true;});await page.click('#demo');await page.$eval('details.help',el=>{el.open=false;});await page.waitForFunction(()=>document.querySelector('#previewAudio').readyState>=1);await page.evaluate(()=>window.scrollTo(0,0));await page.$eval('#preview',el=>el.scrollIntoView({block:'center'}));rect=await page.$eval('#preview',el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height};});await page.touchscreen.tap(rect.x+rect.width*.8,rect.y+rect.height*.5);await page.touchscreen.tap(rect.x+rect.width*.8,rect.y+rect.height*.5);assert.equal(await page.$eval('#scrubber',e=>Number(e.value)),5);
 assert.deepEqual(errors,[]);console.log('PASS integrated: canvas Space once, keyboard skip button, mouse double-tap both sides, float play/pause/drag/resize/hide/reset/restore, mobile touch double-tap; no page errors.');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}})().catch(e=>{console.error(e);process.exitCode=1;});
